version: '3'

services:
  server:
    image: 'mapr/teamcity-server'
    ports:
    - 8111:8111
    volumes:
    - '/root/teamcity_docker/datadir:/data/teamcity_server/datadir'

  agent:
    image: 'jetbrains/teamcity-agent'
    environment:
    - SERVER_URL=server:8111
    volumes:
    - '/root/teamcity_docker/datadir:/data/teamcity_server/datadir'