version: '3'

services:
  server:
    image: 'mapr/teamcity-server'
    ports:
    - 8112:8111
    volumes:
    - '/root/teamcity_docker/datadir:/data/teamcity_server/datadir'
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  agent:
    image: 'mapr/teamcity-agent'
    environment:
    - SERVER_URL=server:8111
    volumes:
    - '/root/teamcity_docker/datadir:/data/teamcity_server/datadir'
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
